services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-api
    restart: on-failure:1
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: postgres:16.10-alpine3.22
    container_name: movies-db
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: 561yem6X56sMfPCopwVwZh
      POSTGRES_DB: movies-db
    ports:
      - '5432:5432'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
