services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-api
    restart: on-failure:1
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: postgres:16.10-alpine3.22
    container_name: movies-db
    restart: on-failure:1
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - '5432:5432'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
